name: Build & Deploy to GitHub Pages

on:
    release:
        types: [released]

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            PUBLIC_SITE_BASE_URL: https://www.jossh.dev

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install Dependencies
              run: bun install --frozen-lockfile

            - name: Run a Check
              run: bun run check

            - name: Vite Build
              run: bun run build

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: build/

    deploy:
        runs-on: ubuntu-latest
        needs: build

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
